# Generated by Django 5.0 on 2023-12-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buy_model',
            fields=[
                ('buy_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.PositiveIntegerField()),
                ('total_price', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phoneno', models.PositiveBigIntegerField()),
                ('order_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='buyed_item_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_id', models.PositiveBigIntegerField()),
                ('item_id', models.PositiveBigIntegerField()),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
