# Generated by Django 5.0 on 2023-12-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_model',
            name='customer_address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
