# Generated by Django 5.0 on 2023-12-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart_model',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.PositiveIntegerField()),
                ('customer_name', models.CharField(max_length=110)),
                ('your_item_id', models.IntegerField()),
                ('your_item_name', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
