# Generated by Django 5.0 on 2023-12-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_model',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='cart_model',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
