# Generated by Django 5.0 on 2023-12-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_alter_cart_model_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_model',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
