# Generated by Django 5.0 on 2023-12-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0004_alter_cart_model_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_model',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
