# Generated by Django 5.0 on 2023-12-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_cart_model_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_model',
            name='hotel_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
