# Generated by Django 5.0 on 2023-12-14 12:10

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='owner_model',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('phone', models.PositiveBigIntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('restarunt_name', models.CharField(max_length=50)),
                ('restarunt_address', models.CharField(max_length=200)),
                ('restarunt_email', models.EmailField(max_length=254, unique=True)),
                ('restarunt_phoneno', models.PositiveBigIntegerField(unique=True)),
                ('restarunt_location', models.CharField(choices=[('punjagutta', 'punjagutta'), ('hitech city', 'hitech city'), ('kphb', 'kphb')], max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('time', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
