# Generated by Django 5.0 on 2023-12-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_model',
            name='date_of_join',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='owner_model',
            name='phone',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
