# Generated by Django 5.0 on 2023-12-12 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_food_model'),
        ('proapp18', '0007_hotel_rating_hotel_register_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_model',
            name='hotel_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proapp18.hotel_register'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food_model',
            name='item_image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
