# Generated by Django 5.0 on 2023-12-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_food_model_hotel_id_food_model_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_model',
            name='category_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
