# Generated by Django 5.0 on 2023-12-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_category_model_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_model',
            name='hotel_id',
        ),
    ]
