# Generated by Django 5.0 on 2023-12-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0005_remove_food_model_hotel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_model',
            name='hotel_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food_model',
            name='hotel_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
