# Generated by Django 5.0 on 2023-12-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0006_category_model_hotel_id_food_model_hotel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_model',
            name='item_quantity',
        ),
    ]
