# Generated by Django 5.0 on 2023-12-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0007_remove_food_model_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_model',
            name='item_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
