# Generated by Django 5.0 on 2023-12-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp18', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restarunt_name', models.CharField(max_length=50)),
                ('restarunt_address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.PositiveBigIntegerField()),
            ],
        ),
    ]
