# Generated by Django 5.0 on 2023-12-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp18', '0002_hotel_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_register',
            name='image',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
