# Generated by Django 5.0 on 2023-12-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp18', '0003_hotel_register_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_register',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
