# Generated by Django 5.0 on 2023-12-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp18', '0004_alter_hotel_register_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_register',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel_register',
            name='phoneno',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
