# Generated by Django 5.0 on 2023-12-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp18', '0005_alter_hotel_register_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_register',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
