# Generated by Django 5.0 on 2023-12-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp18', '0006_alter_hotel_register_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField()),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('comments', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hotel_register',
            name='time',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
